Push ensembles separarate from responses to new storage
equinor/ert pull request #1390
Opened 2021-02-11 07:22 UTC by ManInFez

**Approach**
_Short description of the approach_

2021-02-11 13:32 UTC, ManInFez commented
first step of #1133

2021-02-11 15:28 UTC, oysteoh commented on ert_shared/models/iterated_ensemble_smoother.py
> +                analysis_module_name = self.ert().analysisConfig().activeModuleName()
duplicated line #97

2021-02-12 06:32 UTC, ManInFez commented
Test this please!

2021-02-12 07:40 UTC, oysteoh requested changes
The duplicated line should be fixed, other than that you are good to go from my point of view! 🚀

2021-02-12 07:48 UTC, ManInFez commented on ert_shared/models/iterated_ensemble_smoother.py
> +                analysis_module_name = self.ert().analysisConfig().activeModuleName()
Done!

2021-02-12 07:50 UTC, oysteoh approved these changes

2021-02-12 08:03 UTC, merged