Test extraction
equinor/ert pull request #1711
Opened 2021-05-28 13:14 UTC by oysteoh

2021-06-01 12:22 UTC, xjules commented on tests/storage/test_extraction.py
> +def test_update(client):
Rename `test_post_update_data`

2021-06-02 11:42 UTC, dotfloat requested changes

2021-06-02 11:42 UTC, dotfloat commented on tests/storage/test_extraction.py
> +def test_observation_transformation(client):
Remove this test. It's a WIP and doesn't belong in this PR.

2021-06-02 11:42 UTC, dotfloat commented on tests/storage/test_extraction.py
> +        if path_executable is None:
Job generating code can be moved to `_build_job`, which:
1. Creates a file called `JOB`, pointing to `/usr/bin/true` by default, or to the locally created executable if `self._job_script` is set. The `self._job_script` lets us specify the code for a job to be run.
2. Appends "INSTALL_JOB" and "SIMULATION_JOB" to the ERT config file.

2021-06-02 11:42 UTC, dotfloat commented on tests/storage/test_extraction.py
> +def _create_runpath(ert: LibresFacade, iteration: int = 0, run: bool = False):
`_create_runpath` should just create the runpath. Rename it for the `run` to make sense, or create a separate function called `_evaluate_ensemble`.

2021-06-03 08:23 UTC, xjules commented on tests/storage/test_extraction.py
> +def test_observations(client):
I would also rename this test function to give it more semantics, eg. `test_post_observations`?

2021-06-03 11:34 UTC, dotfloat commented on tests/storage/test_extraction.py
> +    builder._job_script = script
Change `_job_script` to `job_script`. Ie, unprivatise it.

2021-06-03 11:34 UTC, dotfloat commented on tests/storage/test_extraction.py
> +    response_name = "RES"
Style: Move `response_name` to before the `builder` maybe? I personally think it's nicer if we don't mix assigning to constants with other code.

Feel free to ignore. 👍

2021-06-03 11:34 UTC, dotfloat commented on tests/storage/test_extraction.py
> +            (path / "script").write_text(self._job_script)
I think you need `(path / "script").chmod(0o755)`? Or is ERT somehow able to execute it without permissions?

2021-06-03 11:34 UTC, dotfloat commented on ert_shared/models/base_run_model.py
> +from ert3 import algorithms
Unused? Probably shouldn't import from `ert3` in `ert_shared`.

2021-06-03 12:52 UTC, dotfloat approved these changes
👑

2021-06-03 12:54 UTC, merged