Move and rename evaluator tracker to ert/ert
equinor/ert pull request #2903
Opened 2022-02-15 09:15 UTC by Blunde1

**Issue**
Resolves #2894 

**Approach**
- Make early PR to allow discussions on approach
- Move definition of `EvaluatorTracker()` to ert/ert/tracker
- Discuss if this is enough to move, or if more of the tracker module in ert/ert_shared/status/tracker should be moved (i.e., the legacy tracker, factory and utils)
- Create type-hints
- Make tests pass

2022-02-16 10:57 UTC, jondequinor commented on ert/tracker/evaluator_tracker.py
> +    ) -> Iterator[Union[FullSnapshotEvent, SnapshotUpdateEvent, EndEvent]]:
This is actually a generator, which should have the hint structure `Generator[yield_type, send_type, return_type]` so then you get

```python
[Generator[Union[FullSnapshotEvent, SnapshotUpdateEvent, EndEvent], None, None]]
```

See https://docs.python.org/3/library/typing.html#typing.Generator)

2022-02-16 10:58 UTC, jondequinor commented on ert/tracker/evaluator_tracker.py
> +        general_interval: int,
Should be removed, it's probably no longer useful.

2022-02-21 14:45 UTC, sondreso commented
Was confused why Github did not show syntax highlighting, but missing `.py` in the name of the file :sweat_smile:

2022-02-21 18:02 UTC, Blunde1 commented
@xjules could you take a look if this will work with your PR?

2022-02-21 18:09 UTC, jondequinor requested changes
This seems like a copy operation… Do we want two almost identical versions of this tracker? 🤔

2022-02-21 18:28 UTC, Blunde1 commented
> This seems like a copy operation… Do we want two almost identical versions of this tracker? 🤔

@jondequinor Trying to make it work with @xjules' PR https://github.com/equinor/ert/pull/2944, the choice of currently having one for ert2 and one for ert3 is related to this.
It is unmarked as a draft-PR so that it can be tried out by @xjules and then iteratively improving as needed.
Tried rewriting with major changes, i.e. write an implementation that was scaled to current ert3, but it was not beautiful and due to this it made more sense to do revert, take a step back, and do this closely with #2944

2022-02-25 14:00 UTC, closed without merging