Remove UMASK from test data, deprecated
equinor/ert pull request #2921
Opened 2022-02-16 12:32 UTC by berland

**Issue**
Deprecations warning popping out in test runs.

**Approach**
rm

2022-02-18 08:25 UTC, jondequinor approved these changes
Y/n
y

2022-02-18 09:16 UTC, oyvindeide requested changes

2022-02-18 09:16 UTC, oyvindeide commented on libres/old_tests/enkf/CMakeLists.txt
> -  enkf_umask_config
Should delete the .cpp file also: libres/old_tests/enkf/test_enkf_umask_config.cpp

2022-02-18 09:40 UTC, berland commented
Ouch, I think this is hit by #2553

2022-02-18 10:18 UTC, oyvindeide approved these changes

2022-03-03 07:50 UTC, oyvindeide commented
Is it possible to fix? Or should we close this?

2022-03-03 08:00 UTC, berland commented
Closed due to blockage.

2022-03-03 08:00 UTC, closed without merging