Close stdin/stdout/stderr files when done
equinor/ert pull request #3849
Opened 2022-09-01 14:55 UTC by berland

Opted for not using a context manager (ExitStack)
to avoid having to indent all lines in the function

Plus bonus pylinting

**Issue**
Resolves unclosed sdin/stdout/stdin files opened by the `Job` object.

**Approach**
Close at the end.

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

2022-09-05 07:29 UTC, hnformentin commented
Looks good!
(1) Do you think it would make sense to have a test for this?
(2) There is a linting opportunity "Use a single if-statement instead of nested if-statements"  in line 155. Would that make sense to address in this issue?

2022-09-05 11:41 UTC, berland commented
> Looks good! (1) Do you think it would make sense to have a test for this? (2) There is a linting opportunity "Use a single if-statement instead of nested if-statements" in line 155. Would that make sense to address in this issue?

(1): I tried writing a test for this, using `psutil.Process.open_files()` but it turns out that I cannot make this test fail. The reason for  this is that the stdout/stderr handles in the `Job.run()` code goes out of scope and the filehandles are closed by the garbage collector in CPython. So in this case, it is not a problem that the files are not closed, it is more of a recommendation to always close the files.

(2): Fixed!

2022-09-05 12:05 UTC, hnformentin commented on src/ert/job_runner/job.py
> +        # pylint: disable=consider-using-with
What do you think about commenting `# stdin, stout and stderr are closed on the bottom of the function`?

2022-09-05 12:07 UTC, hnformentin commented on src/ert/job_runner/job.py
> +        # pylint: disable=consider-using-with
I just got this idea from your other PR, but it is a minor thing not needed if you prefer so.

2022-09-05 12:21 UTC, hnformentin commented
> > Looks good! (1) Do you think it would make sense to have a test for this? (2) There is a linting opportunity "Use a single if-statement instead of nested if-statements" in line 155. Would that make sense to address in this issue?
> 
> (1): I tried writing a test for this, using `psutil.Process.open_files()` but it turns out that I cannot make this test fail. The reason for this is that the stdout/stderr handles in the `Job.run()` code goes out of scope and the filehandles are closed by the garbage collector in CPython. So in this case, it is not a problem that the files are not closed, it is more of a recommendation to always close the files.
> 
> (2): Fixed!

Nice! It was a good opportunity for me to learn about garbage collector in Python. Thanks for the detailed answer.

2022-09-06 10:46 UTC, hnformentin requested changes
LGTM except for the test failing. Can you please take a look in it?

2022-09-06 12:32 UTC, berland commented
jenkins test this please

2022-09-06 13:47 UTC, berland commented
The failing test looked like Jenkins flakyness, seems ok now.

2022-09-07 05:28 UTC, hnformentin commented
Python coverage / Python Coverage (ert) (pull_request) Cancelled after 30m.
Will restart tests.

jenkins test this please

2022-09-07 05:29 UTC, hnformentin commented
jenkins test this please

2022-09-07 06:57 UTC, hnformentin approved these changes

2022-09-07 08:19 UTC, berland commented
Changing release note label to maintenance since it is not really a bug in CPython as of now.

2022-09-07 08:19 UTC, merged

2022-09-07 08:20 UTC, berland commented
Oh no, forgot to squash!