--workdir changed to -D to increase compatibility
equinor/ert pull request #4189
Opened 2022-11-04 02:40 UTC by pauloestrela

After 17.02 slrum's sbatch command changed the --workdir switch to --chdir, but the short version (-D) remained the same. So, to maintain compatibility with older and newer versions, a better approach is to use -D instead of --workdir.

**Issue**
Resolves #my_issue

**Approach**
_Short description of the approach_

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

2022-11-04 02:41 UTC, ertomatic commented
Can one of the admins verify this patch?

2022-11-04 08:54 UTC, oyvindeide commented
Hi and thanks for the patch! I see the style check is failing, there is a convenience script at `/scripts/clang-format`.

2022-11-04 15:36 UTC, verveerpj requested changes

2022-11-04 15:36 UTC, verveerpj commented on src/clib/lib/job_queue/slurm_driver.cpp
> +        "-D=" + std::string(run_path),
This does not work on the TNO SLUM clusters.

I tested `--chdir` on two SLURM systems that we use at TNO, and that works fine.

Hence, I suggest changing it to `--chdir`.

2022-11-04 15:46 UTC, pauloestrela commented
Which slurm version does TNO slurm use? Because --chdir do not work on versions below 17.02.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: Peter Verveer ***@***.***>
Sent: Friday, November 4, 2022 12:36:27 PM
To: equinor/ert ***@***.***>
Cc: Paulo Jose Braga Estrela ***@***.***>; Author ***@***.***>
Subject: Re: [equinor/ert] --workdir changed to -D to increase compatibility (PR #4189)


@verveerpj requested changes on this pull request.

________________________________

In src/clib/lib/job_queue/slurm_driver.cpp<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fequinor%2Fert%2Fpull%2F4189%23discussion_r1014182046&data=05%7C01%7Cpaulo.estrela%40petrobras.com.br%7Cdeb2872cda5a40beb2e408dabe7a5749%7C5b6f62419a574be48e501dfa72e79a57%7C0%7C0%7C638031729914005789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PMCf3fESTTQTRlo5%2FYuhCRp148JasNem71T37me5gNc%3D&reserved=0>:

> @@ -409,7 +409,7 @@ void *slurm_driver_submit_job(void *__driver, const char *cmd, int num_cpu,
     auto submit_script =
         make_submit_script(driver, cmd, job_name, num_cpu, argc, argv);
     std::vector<std::string> sbatch_argv = {
-        "--workdir=" + std::string(run_path),
+        "-D=" + std::string(run_path),


This does not work on the TNO SLUM clusters.

I tested --chdir on two SLURM systems that we use at TNO, and that works fine.

Hence, I suggest changing it to --chdir.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fequinor%2Fert%2Fpull%2F4189%23pullrequestreview-1168774182&data=05%7C01%7Cpaulo.estrela%40petrobras.com.br%7Cdeb2872cda5a40beb2e408dabe7a5749%7C5b6f62419a574be48e501dfa72e79a57%7C0%7C0%7C638031729914005789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hm29Rlab6WnBX9%2Bh%2Ba2NrriwMgRtjVpTlt9IuJDdWyQ%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACKZXML3D36CFFLPHMMEU5TWGUUPXANCNFSM6AAAAAARWX7Q64&data=05%7C01%7Cpaulo.estrela%40petrobras.com.br%7Cdeb2872cda5a40beb2e408dabe7a5749%7C5b6f62419a574be48e501dfa72e79a57%7C0%7C0%7C638031729914005789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vRz8WHqaLgb1AuIV6mABBsBjqzrnxSubSzL%2Feq89a7g%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

O emitente desta mensagem é responsável por seu conteúdo e endereçamento e deve observar as normas internas da Petrobras. Cabe ao destinatário assegurar que as informações e dados pessoais contidos neste correio eletrônico somente sejam utilizados com o grau de sigilo adequado e em conformidade com a legislação de proteção de dados e privacidade aplicável. A utilização das informações e dados pessoais contidos neste correio eletrônico em desconformidade com as normas aplicáveis acarretará a aplicação das sanções cabíveis.

The sender of this message is responsible for its content and address and must comply with Petrobras' internal rules. It is up to the recipient to ensure that the information and personal data contained in this email are only used with the appropriate degree of confidentiality and in compliance with applicable data protection and privacy legislation. The use of the information and personal data contained in this e-mail in violation of the applicable rules will result in the application of the applicable sanctions.

El remitente de este mensaje es responsable por su contenido y dirección y debe cumplir con las normas internas de Petrobras. Corresponde al destinatario asegurarse de que la información y los datos personales contenidos en este correo electrónico solo se utilicen con el grado adecuado de confidencialidad y de conformidad con la legislación aplicable en materia de privacidad y protección de datos. El uso de la información y datos personales contenidos en este correo electrónico en contravención de las normas aplicables dará lugar a la aplicación de las sanciones correspondientes.


PÚBLICA

2022-11-04 15:49 UTC, verveerpj commented
We use slurm 18.08.8

2022-11-04 16:15 UTC, pauloestrela commented
@verveerpj Could you please try again? I accidentally left a = sign after -D instead of a space character.

2022-11-04 17:05 UTC, oysteoh commented
> @verveerpj Could you please try again? I accidentally left a = sign after -D instead of a space character. I've already committed this change in my fork.

@pauloestrela Could you please also fix the formatting by running the script mentioned by @oyvindeide ?

2022-11-04 17:12 UTC, pauloestrela commented
Sure!

2022-11-04 19:12 UTC, verveerpj commented
Using a space instead if `=` does not work, however you can do this: `"-D", + std::string(run_path)`, i.e. no space and split the string with a comma. I have tested that and it works fine.

2022-11-04 19:17 UTC, oysteoh commented
And please make sure when making the last change to also squash your commits together into one to leave a clean history when merged 👍

2022-11-08 14:09 UTC, oyvindeide commented
@pauloestrela do you have time to update according to the findings in the discussion? Just let us know if we should assist (will keep you as author of course). Think this is a really good contribution, and would be good to include it.

2022-11-08 14:13 UTC, pauloestrela commented
@oyvindeide Yes, I'll to that. I'm little busy right know working with Ketil to make sure that FMU and Drogon model are running well in our environment. Today at afternoon or maybe tomorrow morning I'll work on this PR.

2022-11-08 16:07 UTC, oyvindeide commented
No worries, do it when you have time, and don't hesitate to reach out if you have any questions or need help with anything.

2022-11-25 12:11 UTC, oyvindeide commented
Hi again @pauloestrela, did you have time to look at this?

2022-12-30 14:45 UTC, closed without merging