Type check src/ert/analysis
equinor/ert pull request #4526
Opened 2022-12-30 14:38 UTC by dafeda

**Issue**
Resolves #my_issue

**Approach**
_Short description of the approach_

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

2022-12-30 15:40 UTC, eivindjahren approved these changes

2022-12-30 17:28 UTC, eivindjahren requested changes
I have more of a question that should be resolved before merging: isn't the analysis module checked by the strict check? If it is, there is no need to check it twice.

2022-12-30 19:24 UTC, dafeda commented
> I have more of a question that should be resolved before merging: isn't the analysis module checked by the strict check? If it is, there is no need to check it twice.

Yes you are right. I have removed the extra check but kept the changes to type hints as I think they are better.

2022-12-31 05:27 UTC, eivindjahren approved these changes

2023-01-02 06:05 UTC, merged