Simplify workflow
equinor/ert pull request #4560
Opened 2023-01-05 07:59 UTC by eivindjahren

**Issue**
Resolves #my_issue

**Approach**
_Short description of the approach_

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

2023-01-05 15:02 UTC, valentin-krasontovitsch commented on src/ert/_c_wrappers/util/substitution_list.py
> +            return to_substitute
please change this. : )

2023-01-05 19:04 UTC, valentin-krasontovitsch requested changes
managed to do a proper read through after all - it looks good, and i do have a few comments / suggestions.

2023-01-06 07:08 UTC, eivindjahren commented on src/ert/_c_wrappers/util/substitution_list.py
> +            return to_substitute
Done.

2023-01-06 07:08 UTC, eivindjahren commented on src/ert/_c_wrappers/job_queue/workflow.py
> +    def _try_compile(self, context: Optional["SubstitutionList"]):
Changed it to parse :)

2023-01-06 07:08 UTC, eivindjahren commented on src/ert/_c_wrappers/job_queue/workflow.py
> +            print(list(line))
Removed

2023-01-06 07:08 UTC, eivindjahren commented on src/ert/_c_wrappers/job_queue/workflow.py
> +        return self._compile_time is None
Removed the whole concept of mtime etc.

2023-01-06 07:09 UTC, eivindjahren commented on src/ert/_c_wrappers/util/substitution_list.py
> +            return to_substitute
We could do a `try: ... finally:` I am not worried about running out of tmpdirs though :)

2023-01-06 07:10 UTC, eivindjahren commented on src/ert/_c_wrappers/job_queue/workflow.py
> +            return
I removed the entire concept of trying to cache the compile, I am not convinced it ever happens. So I just made it recompile every time.

2023-01-06 07:44 UTC, valentin-krasontovitsch commented on src/ert/_c_wrappers/util/substitution_list.py
> +            return to_substitute
great then let's just keep it simple and not delete them : )

2023-01-06 08:04 UTC, valentin-krasontovitsch approved these changes
besides the question about logging, this looks good : )

2023-01-06 08:08 UTC, eivindjahren commented on src/ert/_c_wrappers/job_queue/workflow.py
> +            sys.stderr.write(msg.format(self.src_file, err))
It unfortunately does not as warnings are ignored by default.

2023-01-06 08:31 UTC, valentin-krasontovitsch commented on src/ert/_c_wrappers/job_queue/workflow.py
> +            sys.stderr.write(msg.format(self.src_file, err))
ok, I see, but don't we also want to log these using the logger?

2023-01-06 08:45 UTC, merged