Provide better error messages for subst failures
equinor/ert pull request #4576
Opened 2023-01-06 10:44 UTC by eivindjahren

**Issue**
Because of #4566 , we found out that we need better error messages.

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

2023-01-06 11:17 UTC, valentin-krasontovitsch requested changes
can we make it better? give more context? like the whole line?

2023-01-06 11:24 UTC, valentin-krasontovitsch commented
looking at the code, i see that in `config_parser.cpp`, we try to catch the define error, and append it to the parse errors list - but in testing a run, ert just crashes with the runtime error rather than reporting a parse error. is this because i'm trying to create the infinite loop inside arguments of the forward model keyword?

2023-01-06 11:28 UTC, valentin-krasontovitsch commented
python cannot catch a runtime error thrown in C++ code, can it?

2023-01-06 11:39 UTC, oysteoh commented
Seems like it works as intended. My only input would be to slightly modify of of the messages to make it more clear, but i would also accept the current message as good enough :)

2023-01-06 11:41 UTC, oysteoh commented on src/clib/lib/res_util/subst_list.cpp
> +                "Reached max iterations while trying to resolve defines in {}",
Feel this sentence is not fully explaining what is going on - what about `what(): Reached max iterations while trying to resolve DEFINE for string <RMS_PROJECT>`

2023-01-06 13:04 UTC, oysteoh approved these changes

2023-01-06 13:05 UTC, oysteoh commented
Very nice! :rocket:

2023-01-06 13:45 UTC, eivindjahren commented
> python cannot catch a runtime error thrown in C++ code, can it?

Yes, this is the general problem. Attempting to communicate the error up the chain is going to be painful so I think CLI is as good as it gets.

2023-01-06 14:25 UTC, valentin-krasontovitsch commented
turns out if we expose the c/c++ functions through pybind, and throw c++ exceptions, the exceptions get automatically propagated to python and can be caught and handled there. thanks to @pinkwah for the insights! i've created a separate PR where we can try to add some context to the error from further up the calling - #4581

2023-01-06 14:25 UTC, valentin-krasontovitsch approved these changes
looks good!

2023-01-07 11:10 UTC, oysteoh commented
Jenkins: Test this please!

2023-01-09 07:57 UTC, merged