Add ConfigWarning when GEN_DATA INPUT_FORMAT missing or unsupported.
equinor/ert pull request #4965
Opened 2023-02-27 08:16 UTC by DanSava

**Issue**

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

2023-02-28 14:57 UTC, eivindjahren commented on tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
> +def test_gen_data_node_input_format(input_format, expected):
I believe expected is unused here.

2023-02-28 14:57 UTC, eivindjahren requested changes
Just a minor comment on the test, otherwise we are ready to go :)

2023-03-01 08:07 UTC, DanSava commented on tests/unit_tests/c_wrappers/res/enkf/test_ensemble_config.py
> +def test_gen_data_node_input_format(input_format, expected):
That seems to be the case.

2023-03-01 09:19 UTC, eivindjahren approved these changes
:100:

2023-03-01 09:26 UTC, DanSava commented
Jenkins test this please!

2023-03-01 11:42 UTC, merged