Rename instances of test_res_config.py to test_ert_config.py and test_ert_config_parsing.py
equinor/ert pull request #5080
Opened 2023-03-14 08:40 UTC by DanSava

**Approach**
Just simple name refactor 

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

2023-03-14 12:36 UTC, andreas-el requested changes
Can you reword this commit message to be more compact?

The changed files could be listed in the body of the message.
Also, add release skip maybe?

2023-03-14 13:29 UTC, eivindjahren approved these changes

2023-03-14 16:27 UTC, DanSava commented
> Can you reword this commit message to be more compact?
> 
> The changed files could be listed in the body of the message. Also, add release skip maybe?

I guess the changed file names are not really necessary

2023-03-15 07:57 UTC, andreas-el approved these changes
Splendid

2023-03-15 09:54 UTC, merged