add type_hints to analysis_config
equinor/ert pull request #5744
Opened 2023-07-27 13:34 UTC by eivindjahren

**Issue**
Needed for #5214 

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

2023-07-27 13:42 UTC, yngve-sk commented on src/ert/_c_wrappers/enkf/analysis_config.py
> +        analysis_copy: Optional[List[Tuple[str, str]]] = None,
![Screenshot 2023-07-27 at 15 41 45](https://github.com/equinor/ert/assets/11595637/41f625bc-9192-4201-9bd3-7c811719bb8f)

2023-07-27 13:43 UTC, yngve-sk commented on src/ert/_c_wrappers/enkf/analysis_config.py
> +        analysis_set_var: Optional[List[Tuple[str, str, str]]] = None,
![Screenshot 2023-07-27 at 15 41 27](https://github.com/equinor/ert/assets/11595637/c781ca4f-4aaa-4c37-be73-4f64568349da)

2023-07-27 13:45 UTC, yngve-sk commented on src/ert/_c_wrappers/enkf/analysis_config.py
> +        analysis_select: Optional[str] = None,
`Optional[ContextString]`

2023-07-27 13:48 UTC, yngve-sk commented on src/ert/_c_wrappers/enkf/analysis_config.py
> +        num_realization: int = config_dict.get(ConfigKeys.NUM_REALIZATIONS, 1)  # type: ignore
Some of these are Context'ed but some tests also initialize from dict without originating from file, so not sure which one is more practical/correct. Context* if file origin is always assumed.

![Screenshot 2023-07-27 at 15 48 03](https://github.com/equinor/ert/assets/11595637/71078970-3ad5-464b-8f86-e6618d711d7b)

2023-07-27 13:52 UTC, yngve-sk requested changes
Looks good overall, please do a double check and consider whether the typings should be using the context'ed values as they do show up in some places when running this

2023-07-28 06:11 UTC, eivindjahren commented
> Looks good overall, please do a double check and consider whether the typings should be using the context'ed values as they do show up in some places when running this

I looked a bit closer at it, and I don't think its a good idea to check the TypeDict portion just yet. I think we can more easily handle this by simplifying the ErrorInfo object a bit now that we are just using the new parser. Then you can have a look at whether that solves the issue.

2023-07-28 06:20 UTC, yngve-sk approved these changes
LGTM🚀

2023-07-28 06:25 UTC, merged