Docs getting started
equinor/ert pull request #5852
Opened 2023-08-09 17:34 UTC by dafeda

**Issue**
Resolves #my_issue

**Approach**
_Short description of the approach_

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

2023-08-15 11:48 UTC, jonathan-eq requested changes

2023-08-15 11:59 UTC, dafeda commented on docs/getting_started/configuration/poly_new/guide.rst
Thanks, fixed

2023-08-16 06:24 UTC, jonathan-eq approved these changes

2023-08-16 06:24 UTC, jonathan-eq commented
LGTM!

2023-08-16 06:28 UTC, merged