Prevent empty enviroment variables
equinor/ert pull request #6051
Opened 2023-09-05 12:29 UTC by larsevj

**Issue**
Resolves #6031 

**Approach**
_Short description of the approach_

## Pre review checklist

- [ ] Read through the code changes carefully after finishing work
- [ ] Make sure tests pass locally (after every commit!)
- [ ] Prepare changes in small commits for more convenient review (optional)
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested (opened GUI? screenshots? tried workflows?)

## Pre merge checklist
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

2023-09-19 10:56 UTC, oysteoh commented on src/ert/config/queue_config.py
> +                        f"{values[0]}. Check for empty enviroment variable. "
enviroment -> environment

"The LSF_SERVER is usually specified in the site-config file. "  - maybe more like something like this? 
"The LSF_SERVER value is usually provided by default in a site-configuration file. If you have no special needs you can safely remove it from your configuration"

2023-09-25 10:36 UTC, andreas-el commented on src/ert/config/queue_config.py
> +                        f" {values[0]}. Check for empty environment variable. The"
Is the environment variable empty? Or is it just not set?

2023-09-26 07:15 UTC, andreas-el commented on src/ert/config/queue_config.py
> +                        " can safely remove it from your configuration."
This is obviously up for discussion but you could consider something like this?
```
"Invalid server name specified for QUEUE_OPTION LSF LSF_SERVER:"
f" {values[0]}. Server name is currently an undefined environment variable. "
"The LSF_SERVER keyword is usually provided by the site-configuration file, "
"beware that you are effectively replacing the default value provided."
```

2023-09-26 07:20 UTC, andreas-el requested changes
Please take a look at the feedback provided.

PR-name and commit is done perfectly. 🚀

2023-09-26 08:14 UTC, andreas-el approved these changes
You nailed it! 🚀

2023-09-26 12:40 UTC, merged