Clarify outlier/low variability detection warnings ES
equinor/ert pull request #6512
Opened 2023-11-07 12:30 UTC by yngve-sk

**Issue**
Resolves #6262

2023-11-07 14:38 UTC, oyvindeide commented
Note that some of this information is also available in the update snapshot: https://github.com/equinor/ert/blob/9f7ac75b4a8a6285659bb1ba641c14a2f9b79ec7/src/ert/analysis/_es_update.py#L60-L67 which is written out after an update, so might make sense to gather this information more.

2023-11-08 07:03 UTC, yngve-sk commented
> Note that some of this information is also available in the update snapshot:
> 
> https://github.com/equinor/ert/blob/9f7ac75b4a8a6285659bb1ba641c14a2f9b79ec7/src/ert/analysis/_es_update.py#L60-L67
> 
> which is written out after an update, so might make sense to gather this information more.

I see, will try to gather it there, I think it also then makes sense to silence the original warning, ref this [slack convo](https://equinor.slack.com/archives/CDPJULWR4/p1696423905046869) where user gets many of these messages and wonders why they were disabled.

2023-11-17 12:24 UTC, andreas-el commented on src/ert/analysis/_es_update.py
> +                f" setting  the ENKF_ALPHA parameter in the ert config."
Extra space after first word on this line

2024-01-23 08:32 UTC, oyvindeide commented
Would be great to add this in the update snapshot instead of in the log, so we get a column there with the index.

2024-01-31 15:18 UTC, oyvindeide requested changes
Looks like a good change! Should also include it in the update report in the gui, and some other small comments.

2024-01-31 15:18 UTC, oyvindeide commented on src/ert/analysis/_es_update.py
> +                    f"{k}:{v}" for k, v in coord_cpy.items() if k != "name"
Checking for key here, even though it is deleted.

2024-01-31 15:18 UTC, oyvindeide commented on src/ert/analysis/_es_update.py
> +                    f"{k}:{v}" for k, v in coord_cpy.items() if k != "name"
Is it possible to do this when extracting it in the first place? And just return the completed `index` string instead? Think that makes it easier to read.

2024-01-31 15:18 UTC, oyvindeide commented on src/ert/analysis/_es_update.py
> +                    f"{k}:{v}" for k, v in coord_cpy.items() if k != "name"
That would also make it easier to include it in the update report in the gui:
![image](https://github.com/equinor/ert/assets/44577479/9bab9249-b5e7-4b27-8d97-0e2472a347ae)

2024-08-07 07:27 UTC, sondreso commented
Closing this as the original issue has been fixed: https://github.com/equinor/ert/issues/6262

2024-08-07 07:27 UTC, closed without merging