Fix an issue where summary keys were not consistently named
equinor/ert pull request #6932
Opened 2024-01-12 12:12 UTC by eivindjahren

Ensure consistent naming of summary keys. This also fixes an issue
where history keys were not handled correctly: e.g.

the history key of "BOPR:1,1,3" was before interpreted to be
"BOPR:1,1,3H" but is now interpreted as "BOPRH:1,1,3".

Whether that always makes sense in all simulators is not confirmed, but
it "BOPR:1,1,3H" is guaranteed to not be found in the summary file. The
keys that did work correctly before, `FIELD`, `OTHER`, `GROUP` and `WELL`
still works the same way.

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

2024-01-15 07:03 UTC, andreas-el commented on src/ert/config/ert_config.py
> +            obs_time_list = [refcase[0]] + list(refcase[2])
This is so because of startdate, timemap ?

2024-01-15 07:18 UTC, andreas-el commented on src/ert/config/ensemble_config.py
> +                        del to_add[i]
Ok since we are reversing iteration

2024-01-15 07:23 UTC, andreas-el requested changes
This is definitely moving in the right direction, but there are some failing tests that needs to be resolved at a minimum.

2024-01-15 07:34 UTC, eivindjahren commented on src/ert/config/ensemble_config.py
> +                        del to_add[i]
Yup.

2024-01-17 07:24 UTC, andreas-el approved these changes
Great! 🚀

2024-01-17 09:36 UTC, merged