Rename Snapshot to EnsembleSnapshot
equinor/ert pull request #8669
Opened 2024-09-09 12:59 UTC by JHolba

- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

2024-09-10 06:29 UTC, jonathan-eq commented on src/ert/ensemble_evaluator/_ensemble.py
> +            for index, forward_model in enumerate(real.fm_steps):
```suggestion
            for index, forward_model_step in enumerate(real.fm_steps):
```

2024-09-10 06:31 UTC, jonathan-eq commented on src/ert/ensemble_evaluator/evaluator.py
> +        for job in self.ensemble.snapshot.get_all_fm_steps().values():
```suggestion
        for forward_model_step in self.ensemble.snapshot.get_all_fm_steps().values():
```

2024-09-10 06:34 UTC, jonathan-eq commented on src/ert/ensemble_evaluator/snapshot.py
> +class EnsembleSnapshot:
Fantastic :)

2024-09-10 06:40 UTC, jonathan-eq commented on src/ert/ensemble_evaluator/snapshot.py
>      ) -> Mapping[Tuple[str, str], str]:
```suggestion
    ) -> Mapping[Tuple[RealId, FmStepId], str]:
```

2024-09-10 06:44 UTC, jonathan-eq commented on src/ert/ensemble_evaluator/snapshot.py
> +        for real_id, realization_data in snapshot.get("reals", {}).items():
```suggestion
    def from_nested_dict(cls, input_dict: Mapping[Any, Any]) -> "EnsembleSnapshot":
        new_snapshot = EnsembleSnapshot()
        if "metadata" in input_dict:
            new_snapshot._metadata = input_dict["metadata"]
        if "status" in snapshot:
            new_snapshot._ensemble_state = input_dict["status"]
        for real_id, realization_data in input_dict.get("reals", {}).items():
```

2024-09-10 06:45 UTC, jonathan-eq commented on src/ert/ensemble_evaluator/snapshot.py
>      def reals(self) -> Mapping[str, "RealizationSnapshot"]:
```suggestion
    def reals(self) -> Mapping[RealId, "RealizationSnapshot"]:
```

2024-09-10 07:35 UTC, JHolba commented on src/ert/gui/model/job_list.py
> +    FM_STEP_COLUMN_SIZE,
good point. renamed it.

2024-09-10 08:02 UTC, JHolba commented on src/ert/ensemble_evaluator/snapshot.py
>      ) -> Mapping[Tuple[str, str], str]:
fixed

2024-09-10 08:04 UTC, JHolba commented on src/ert/ensemble_evaluator/snapshot.py
> +        for real_id, realization_data in snapshot.get("reals", {}).items():
changed it from snapshot to source

2024-09-10 08:05 UTC, JHolba commented on src/ert/ensemble_evaluator/snapshot.py
>      def reals(self) -> Mapping[str, "RealizationSnapshot"]:
fixed

2024-09-10 10:55 UTC, xjules commented
Not sure if required, but this has file/test has not been touched `tests/integration_tests/test_cli.py::test_that_log_is_cleaned_up_from_repeated_forward_models`

2024-09-11 05:41 UTC, jonathan-eq requested changes
Tests broke

2024-09-11 06:41 UTC, jonathan-eq approved these changes
Very good!

2024-09-11 06:45 UTC, merged