Fix restart experiment by updating shapshot only
equinor/ert pull request #8692
Opened 2024-09-13 11:30 UTC by xjules

**Issue**
Resolves https://github.com/equinor/ert/issues/8032

**Approach**
When restart happens just re-use the old snapshot model.

(Screenshot of new behavior in GUI if applicable)

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

2024-09-16 07:58 UTC, jonathan-eq commented on src/ert/run_models/base_run_model.py
> +        # realization_count = len(all_realizations)
```suggestion
```

2024-09-16 07:58 UTC, jonathan-eq commented on src/ert/run_models/base_run_model.py
> +            # realization_progress = float(done_realizations) / len(all_realizations)
```suggestion
```

2024-09-16 10:17 UTC, jonathan-eq requested changes
Looks very good, just remove the comments and we are ready to merge 🚗 💨

2024-09-16 10:18 UTC, jonathan-eq commented
Also, should we change the button text? `Restart` can be misinterpreted, and should in this case be something along the lines of `Restart failed realizations`.

2024-09-23 06:32 UTC, xjules commented
> Also, should we change the button text? `Restart` can be misinterpreted, and should in this case be something along the lines of `Restart failed realizations`.

Hm, the button would become quite huge wouldn't it? :)

2024-09-23 06:54 UTC, jonathan-eq commented
> > Also, should we change the button text? `Restart` can be misinterpreted, and should in this case be something along the lines of `Restart failed realizations`.
> 
> Hm, the button would become quite huge wouldn't it? :)

Yes, we would have to rephrase it for something better 🤔

2024-09-25 05:33 UTC, jonathan-eq approved these changes
Looks great to me! ☘️

2024-09-25 07:13 UTC, xjules commented
New screenshot:

![image](https://github.com/user-attachments/assets/73110f3e-5ddd-4d66-8556-b86588a2dafe)

2024-09-25 07:25 UTC, merged