Set ensemble_size dynamically for each batch
equinor/ert pull request #9012
Opened 2024-10-21 14:24 UTC by StephanDeHoop

**Issue**
Resolves #8848

**Approach**
Remove the default number of realizations and set it dynamically for each batch when a new ensemble is created. Also, for completeness still setting number of realizations equal to length of the realization list in the config file (Ert **AnalysisConfig** and **ModelConfig** still use the config dictionary and ConfigKeys.NUM_REALIZATIONS to set the num_realizations field. If we know how many realizations there are, why not set is correctly was my logic. Also cleaned up the hard coded strings by importing the Ert ConfigKeys. 

(Screenshot of new behavior in GUI if applicable)

- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure unit tests pass locally after every commit (`git rebase -i main
      --exec 'pytest tests/ert/unit_tests -n logical -m "not integration_test"'`)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

2024-10-22 07:07 UTC, verveerpj approved these changes
LGTM!

2024-10-22 07:12 UTC, yngve-sk requested changes
I would rebase the commits so you have the introducing of ConfigKeysErt completely separate from the changing of the default value, the commit with the test fixup now relates to both of these things, it would be nice to have it in sequence and not intermingled. Maybe a bit of a nitpick but I'm not sure about this practice of using these "string enums" in general to access the dicts.

2024-10-22 07:24 UTC, verveerpj commented
> I would rebase the commits so you have the introducing of ConfigKeysErt completely separate from the changing of the default value, the commit with the test fixup now relates to both of these things, it would be nice to have it in sequence and not intermingled. Maybe a bit of a nitpick but I'm not sure about this practice of using these "string enums" in general to access the dicts.

That is a very good point. Should we really use these enums? Maybe we can discuss this in the standup.

2024-10-23 08:44 UTC, yngve-sk approved these changes

2024-10-23 09:25 UTC, merged