Remove SIMULATION_JOB keyword
equinor/ert pull request #9606
Opened 2024-12-20 11:34 UTC by DanSava

**Issue**
Resolves #4955 

- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure unit tests pass locally after every commit (`git rebase -i main
      --exec 'pytest tests/ert/unit_tests -n logical -m "not integration_test"'`)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

2025-01-06 11:35 UTC, verveerpj approved these changes
LGTM!

2025-01-06 14:13 UTC, oyvindeide requested changes
Looks really nice, but would be great with a migration error with a path to resoluation if anyone is using this, it will currently just show up as a warning.

2025-01-07 10:37 UTC, oyvindeide approved these changes
LGTM! Just a minor comment, is it possible to write out an example of how `FORWARD_MODEL` should be configured with the same args?

2025-01-07 10:37 UTC, oyvindeide commented on src/ert/config/parsing/config_schema_deprecations.py
> +        "FORWARD_MODEL. Please use FORWARD_MODEL keyword instead.",
```suggestion
        "effect. Please use FORWARD_MODEL keyword instead:"
        f"FORWARD_MODEL {args}",
```

2025-01-07 12:16 UTC, merged